// src/services/products.service.ts
// Products service — auto-generated by street generate.

import { Injectable } from 'streetjs';
import { ProductsRepository } from '../repositories/products.repository.js';

export interface Products {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  [key: string]: unknown;
}

@Injectable()
export class ProductsService {
  constructor(private readonly repository: ProductsRepository) {}

  async findAll(page: number, limit: number) {
    return this.repository.findAll(page, limit);
  }

  async findById(id: string): Promise<Products | null> {
    return this.repository.findById(id);
  }

  async create(input: Record<string, unknown>): Promise<Products> {
    const now = new Date();
    const item: Products = {
      id: crypto.randomUUID(),
      ...input,
      createdAt: now,
      updatedAt: now,
    };
    await this.repository.create(item);
    return item;
  }

  async update(id: string, input: Record<string, unknown>): Promise<Products | null> {
    const existing = await this.repository.findById(id);
    if (!existing) return null;

    const updated: Products = {
      ...existing,
      ...input,
      updatedAt: new Date(),
    };
    await this.repository.update(updated);
    return updated;
  }

  async delete(id: string): Promise<void> {
    await this.repository.delete(id);
  }
}
