// src/controllers/products.controller.ts
// Products controller — auto-generated by street generate.

import { Controller, Get, Post, Put, Delete, ApiOperation } from 'streetjs';
import type { StreetContext } from 'streetjs';
import { ProductsService } from '../services/products.service.js';
import { container } from 'streetjs';

@Controller('/api/products')
export class ProductsController {
  private readonly service = container.resolve(ProductsService);

  @Get('/')
  @ApiOperation({ summary: 'List all productss', tags: ['products'] })
  async findAll(ctx: StreetContext): Promise<void> {
    const page = parseInt(ctx.query['page'] ?? '1', 10);
    const limit = parseInt(ctx.query['limit'] ?? '20', 10);
    const result = await this.service.findAll(page, limit);
    ctx.json(result);
  }

  @Get('/:id')
  @ApiOperation({ summary: 'Get products by ID', tags: ['products'] })
  async findById(ctx: StreetContext): Promise<void> {
    const id = ctx.params['id'];
    if (!id) {
      ctx.json({ error: 'Missing id parameter' }, 400);
      return;
    }
    const item = await this.service.findById(id);
    if (!item) {
      ctx.json({ error: 'Products not found' }, 404);
      return;
    }
    ctx.json(item);
  }

  @Post('/')
  @ApiOperation({ summary: 'Create a products', tags: ['products'] })
  async create(ctx: StreetContext): Promise<void> {
    const data = ctx.body as Record<string, unknown> | null;
    if (!data || typeof data !== 'object') {
      ctx.json({ error: 'Invalid request body' }, 400);
      return;
    }
    const item = await this.service.create(data);
    ctx.json(item, 201);
  }

  @Put('/:id')
  @ApiOperation({ summary: 'Update a products', tags: ['products'] })
  async update(ctx: StreetContext): Promise<void> {
    const id = ctx.params['id'];
    const data = ctx.body as Record<string, unknown> | null;
    if (!id || !data) {
      ctx.json({ error: 'Missing id or body' }, 400);
      return;
    }
    const item = await this.service.update(id, data);
    if (!item) {
      ctx.json({ error: 'Products not found' }, 404);
      return;
    }
    ctx.json(item);
  }

  @Delete('/:id')
  @ApiOperation({ summary: 'Delete a products', tags: ['products'] })
  async delete(ctx: StreetContext): Promise<void> {
    const id = ctx.params['id'];
    if (!id) {
      ctx.json({ error: 'Missing id parameter' }, 400);
      return;
    }
    await this.service.delete(id);
    ctx.send(204);
  }
}
